version: '3.7'
services:
  campaign-service:
    image: campaign-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: